{
  "openapi":"3.0.2",
  "info": {
    "title":"Chatter",
    "version":"1.0",
    "license": {
      "name": "MIT",
      "url": "https://raw.githubusercontent.com/DiegoVictor/chatter/main/LICENSE"
    }
  },
  "servers": [
    {
      "url":"http://localhost:3333/v1"
    }
  ],
  "paths": {
    "/users": {
      "post": {
        "tags": ["Users"],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "title": "User",
                "required": ["email"],
                "properties": {
                  "email": {
                    "type": "string"
                  }
                }
              },
              "example": {
                "email": "johndoe@example.com"
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Create a new user",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/User"
                },
                "example": {
                  "id": "17c6f66d-a24b-45e0-8c3f-2b3411e51fe8",
                  "email": "johndoe@example.com",
                  "created_at": "2021-08-29T19:05:04.000Z"
                }
              }
            }
          }
        }
      }
    },
    "/users/{id}/messages": {
      "get": {
        "tags": ["Users"],
        "parameters": [
          {
            "in": "path",
            "name": "id",
            "required": true,
            "schema": {
              "type": "string"
            },
            "example": "17c6f66d-a24b-45e0-8c3f-2b3411e51fe8"
          }
        ],
        "responses": {
          "200": {
            "description": "Return user's messages",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "allOf": [
                      {
                        "$ref": "#/components/schemas/Message"
                      },
                      {
                        "title": "Message",
                        "properties": {
                          "user": {
                            "$ref": "#/components/schemas/User"
                          }
                        }
                      }
                    ]
                  }
                },
                "example": [
                  {
                    "id": "4fdbfa46-7a05-4bed-b4a0-b6f1d354b261",
                    "user_id": "17c6f66d-a24b-45e0-8c3f-2b3411e51fe8",
                    "admin_id": "aa199c1f-59e3-403b-9adf-3035b1bcd16a",
                    "text": "Lorem ipsum dolor sit amet",
                    "created_at": "2021-08-29T19:14:05.000Z",
                    "user": {
                      "id": "17c6f66d-a24b-45e0-8c3f-2b3411e51fe8",
                      "email": "johndoe@example.com",
                      "created_at": "2021-08-29T19:05:04.000Z"
                    }
                  }
                ]
              }
            }
          },
          "404": {
            "description": "User not found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error"
                },
                "example": {
                  "statusCode": 404,
                  "error": "Not Found",
                  "message": "User not found",
                  "code": 245,
                  "docs": "https://github.com/DiegoVictor/chatter#errors-reference"
                }
              }
            }
          }
        }
      }
    },
    "/messages": {
      "post": {
        "tags": ["Messages"],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "title": "Message",
                "required": [
                  "user_id",
                  "admin_id",
                  "text"
                ],
                "properties": {
                  "user_id": {
                    "type": "string"
                  },
                  "admin_id": {
                    "type": "string"
                  },
                  "text": {
                    "type": "string"
                  }
                }
              },
              "example": {
                "admin_id": "181e7e4e-9b06-47e3-8105-92584459c53e",
                "text": "Lorem ipsum dolor sit amet",
                "user_id": "17c6f66d-a24b-45e0-8c3f-2b3411e51fe8"
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Save user new message",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Message"
                },
                "example": {
                  "id": "b485dbcf-3c64-4de1-bfb3-5187568bdc78",
                  "user_id": "17c6f66d-a24b-45e0-8c3f-2b3411e51fe8",
                  "admin_id": "181e7e4e-9b06-47e3-8105-92584459c53e",
                  "text": "Lorem ipsum dolor sit amet",
                  "created_at": "2021-08-29T19:21:49.000Z"
                }
              }
            }
          },
          "404": {
            "description": "User not found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error"
                },
                "example": {
                  "statusCode": 404,
                  "error": "Not Found",
                  "message": "User not found",
                  "code": 244,
                  "docs": "https://github.com/DiegoVictor/chatter#errors-reference"
                }
              }
            }
          }
        }
      }
    },
    "/settings": {
      "post": {
        "tags": ["Settings"],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "title": "Settings",
                "required": [
                  "user_id",
                  "chat"
                ],
                "properties": {
                  "user_id": {
                    "type": "string"
                  },
                  "chat": {
                    "type": "boolean"
                  }
                }
              },
              "example": {
                "user_id": "17c6f66d-a24b-45e0-8c3f-2b3411e51fe8",
                "chat": true
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Create new setting",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Settings"
                },
                "example": {
                  "id": "e7d7d0f2-80c2-4472-ae50-64aaaa94f30e",
                  "username": "johndoe",
                  "chat": true,
                  "created_at": "2021-08-29T19:27:06.000Z",
                  "updated_at": "2021-08-29T19:27:06.000Z"
                }
              }
            }
          },
          "400": {
            "description": "Setting already exists",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error"
                },
                "example": {
                  "statusCode": 400,
                  "error": "Bad Request",
                  "message": "Setting already exists",
                  "code": 140,
                  "docs": "https://github.com/DiegoVictor/chatter#errors-reference"
                }
              }
            }
          }
        }
      }
    },
    "/settings/{id}": {
      "get": {
        "tags": ["Settings"],
        "parameters": [
          {
            "in": "path",
            "name": "id",
            "required": true,
            "schema": {
              "type": "string"
            },
            "example": "c9b458a3-556e-4c33-9aa1-d60f78f44b90"
          }
        ],
        "responses": {
          "200": {
            "description": "Return the user's setting",
            "content": {
              "application/json": {
                "example": {
                  "id": "c9b458a3-556e-4c33-9aa1-d60f78f44b90",
                  "user_id": "17c6f66d-a24b-45e0-8c3f-2b3411e51fe8",
                  "chat": true,
                  "created_at": "2021-08-29T19:46:41.000Z",
                  "updated_at": "2021-08-29T19:46:41.000Z"
                }
              }
            }
          }
        }
      },
      "put": {
        "tags": ["Settings"],
        "parameters": [
          {
            "in": "path",
            "name": "id",
            "required": true,
            "schema": {
              "type": "string"
            },
            "example": "c9b458a3-556e-4c33-9aa1-d60f78f44b90"
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "chat": {
                    "type": "boolean"
                  }
                }
              },
              "example": {
                "chat": true
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Update an user's setting",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Settings"
                },
                "example": {
                  "id": "2096f290-7b40-47cd-bb7d-a43812b93acc",
                  "user_id": "0e7c0594-170d-4587-bb85-626bd480e5a7",
                  "chat": true,
                  "created_at": "2021-08-29T19:54:04.000Z",
                  "updated_at": "2021-08-29T19:54:04.000Z"
                }
              }
            }
          },
          "404": {
            "description": "Setting not found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error"
                },
                "example": {
                  "statusCode": 404,
                  "error": "Not Found",
                  "message": "Setting not found",
                  "code": 144,
                  "docs": "https://github.com/DiegoVictor/chatter#errors-reference"
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "User": {
        "properties": {
          "id": {
            "type": "string"
          },
          "email": {
            "type": "string"
          },
          "created_at": {
            "type": "string"
          }
        }
      },
      "Message": {
        "properties": {
          "id": {
            "type": "string"
          },
          "user_id": {
            "type": "string"
          },
          "admin_id": {
            "type": "string"
          },
          "text": {
            "type": "string"
          },
          "created_at": {
            "type": "string"
          }
        }
      },
      "Settings": {
        "properties": {
          "id": {
            "type": "string"
          },
          "user_id": {
            "type": "string"
          },
          "chat": {
            "type": "boolean"
          },
          "created_at": {
            "type": "string"
          },
          "updated_at": {
            "type": "string"
          }
        }
      },
      "Error": {
        "properties": {
          "statusCode": {
            "type": "integer"
          },
          "error": {
            "type": "string"
          },
          "message": {
            "type": "string"
          },
          "code": {
            "type": "integer"
          },
          "docs": {
            "type": "string"
          }
        }
      }
    }
  }
}
